// Auto-generated one-time seed data for the Purchase Order system.
// Parsed and deduplicated from ACS Beverage Co.'s real historical PO archive (2024-2025).
// Safe to run multiple times -- the import route checks for existing suppliers/products by name.
module.exports = [
  { name: 'ATC Wines', paymentTerms: 'Net 30', products: [
    { description: 'Beau Vigne Hero 2022 12/750ml', brandName: '', vintage: '2022', type: 'Wine', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 72.0, bottlePrice: 6.0 },
    { description: 'Dolum Estates Cask 11 Cabernet Sauvignon Sonoma County 2022 12/750ml', brandName: '', vintage: '2022', type: 'Wine', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 132.0, bottlePrice: 11.0 },
    { description: 'Beau Vigne Romeo Cabernet Sauvignon Napa Valley 2022 12/750ml', brandName: '', vintage: '2022', type: 'Wine', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 348.0, bottlePrice: 29.0 },
    { description: 'Beau Vigne Hero 2023 12/750ml (2023)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 72.0, bottlePrice: 6.0 },
  ]},
  { name: 'Aguirre Tequila Imports', paymentTerms: 'Net 30', products: [
    { description: 'Lost Lore Tequila Blanco 6/750', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 162.0, bottlePrice: 27.0 },
    { description: 'Lost Lore Tequila Reposado 6/750', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 195.0, bottlePrice: 32.5 },
    { description: 'Lost Lore Tequila Anejo 6/750', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 276.0, bottlePrice: 46.0 },
    { description: 'Lost Lore Reposado Amburana Cask', brandName: 'Lost Lore Tequila', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 257.0, bottlePrice: 42.83 },
    { description: 'Lost Lore Single Barrel Reposado " Pyrola/Roadrunner"', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 264.0, bottlePrice: 44.0 },
    { description: 'Lost Lore Blanco', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 162.0, bottlePrice: 27.0 },
    { description: 'Lost Lore Reposado', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 195.0, bottlePrice: 32.5 },
    { description: 'Lost Lore Anejo', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 276.0, bottlePrice: 46.0 },
    { description: 'Lost Lore Tequila Joven', brandName: 'Lost Lore Tequila', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 195.0, bottlePrice: 32.5 },
    { description: 'Lost Lore Tequila Blanco', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 162.0, bottlePrice: 27.0 },
    { description: 'Lost Lore Tequila Reposado', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 195.0, bottlePrice: 32.5 },
    { description: 'Lost Lore Tequila Anejo', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 276.0, bottlePrice: 46.0 },
    { description: 'Lost Lore Tequila Joven 6/750ml', brandName: 'Lost Lore', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 195.0, bottlePrice: 32.5 },
    { description: 'Lost Lore Tequila Tahona Blanco 6/750', brandName: 'Lost Lore', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 262.0, bottlePrice: 43.67 },
    { description: 'Lost Lore Tequila High Proof Reposado 2025 Edition 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 262.0, bottlePrice: 43.67 },
    { description: 'Lost Lore Tequila Blanco (OP only)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 190.0, bottlePrice: 15.83 },
    { description: 'Lost Lore Tequila Valley Blanco 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 225.0, bottlePrice: 37.5 },
    { description: 'Lost Lore Rested Series Bottle Logic Single Barrel Reposado 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 240.0, bottlePrice: 40.0 },
    { description: 'Lost Lore Tequila Blanco (OP) 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 190.0, bottlePrice: 15.83 },
  ]},
  { name: 'Alta Winery', paymentTerms: 'Net 60', products: [
    { description: 'Alta Pinot Noir 2019 Carneros', brandName: '', vintage: null, type: 'Wine', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 120.0, bottlePrice: 20.0 },
    { description: 'Alta Chardonnay 2021 12/750ml', brandName: 'Alta', vintage: '2021', type: 'Chardonnay', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 84.0, bottlePrice: 7.0 },
    { description: 'Alta Russian River Pinot Noir 2019 12/750ml', brandName: 'Alta', vintage: '2019', type: 'Pinot Noir', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 84.0, bottlePrice: 7.0 },
  ]},
  { name: 'American Spirits Exchange', paymentTerms: 'Net 45', products: [
    { description: 'La Madrina Acholado', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 115.0, bottlePrice: 19.17 },
    { description: 'La Madrina Torontel', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 115.0, bottlePrice: 19.17 },
    { description: 'La Madrina Quebranta', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 105.0, bottlePrice: 17.5 },
    { description: 'La Madrina Mosto Verde Torontel', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 165.0, bottlePrice: 27.5 },
    { description: 'La Madrina Pisco Acholado 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 115.0, bottlePrice: 19.17 },
    { description: 'La Madrina Pisco Torontel 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 115.0, bottlePrice: 19.17 },
    { description: 'La Madrina Pisco Quebranta 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 105.0, bottlePrice: 17.5 },
    { description: 'Sacred Valley Pisco Quebranta 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 80.0, bottlePrice: 13.33 },
    { description: 'MANUSCRITO BLANCO 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 150.0, bottlePrice: 25.0 },
    { description: 'MANUSCRITO HIGH PROOF 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 186.0, bottlePrice: 31.0 },
    { description: 'Manuscrito Blanco (Chapter 1) 6/750 ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 150.0, bottlePrice: 25.0 },
    { description: 'Manuscrito Blanco High Proof (Chapter 2) 6/750 ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 186.0, bottlePrice: 31.0 },
    { description: 'Primo 1861 Tequila Blanco 40% 6/750ml', brandName: 'Tequila Primo 1861', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 172.18, bottlePrice: 28.7 },
    { description: 'Primo 1861 Tequila Reposado 40% 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 203.28, bottlePrice: 33.88 },
    { description: 'Primo 1861 Tequila Blanco High Proof 50% 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 203.28, bottlePrice: 33.88 },
    { description: 'Sacred Valley Pisco Quebranta 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 80.0, bottlePrice: 13.33 },
    { description: 'Manuscrito Reposado (Chapter 3) 6/750 ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 165.0, bottlePrice: 27.5 },
    { description: 'Manuscrito Reposado High Proof (Chapter 4) 6/750 ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 200.0, bottlePrice: 33.33 },
  ]},
  { name: 'Ascend Beverage Co. / SunGod', paymentTerms: 'Net 45', products: [
    { description: 'SunGod Minted-Sol 6/4pks', brandName: '', vintage: null, type: 'Spirits', bottleSize: '12oz', bottlesPerCase: 6, casePrice: 41.82, bottlePrice: 1.74 },
    { description: 'SunGod Solar-Drift 6/4pks', brandName: '', vintage: null, type: 'Spirits', bottleSize: '12oz', bottlesPerCase: 6, casePrice: 41.82, bottlePrice: 1.74 },
  ]},
  { name: 'Boone\'s Bourbon', paymentTerms: 'Net 30', products: [
    { description: 'Boone\'s Bourbon 117 Proof Small Batch Barrel Proof 120/50ml', brandName: 'Boone\'s Bourbon', vintage: null, type: 'Spirits', bottleSize: '50ml', bottlesPerCase: 6, casePrice: 180.0, bottlePrice: 1.5 },
    { description: 'Boone\'s Bourbon 117 Proof Small Batch Barrel Proof 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 120.0, bottlePrice: 20.0 },
  ]},
  { name: 'Casa Mate', paymentTerms: 'Net 60', products: [
    { description: 'Casa Mate Tequila', brandName: 'Casa Mate', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 170.0, bottlePrice: 28.33 },
  ]},
  { name: 'Cascade Wine & Spirits', paymentTerms: 'Net 45', products: [
    { description: 'Wild Roots Pear Vodka 6/750ml', brandName: 'Wild Roots', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Huckleberry Vodka 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Marionberry Vodka 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Peach Vodka 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Vodka 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 68.0, bottlePrice: 11.33 },
    { description: 'Wild Roots Raspberry Vodka 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots London Dry Gin 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 68.0, bottlePrice: 11.33 },
    { description: 'Wild Roots Orange & Bergamont Gin 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Cucumber & Grapefruit Gin 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Marionberry Infused Vodka 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Orange & Bergamot Infused Gin 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Raspberry Infused Vodka 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Apple & Cinnamon Infused Vodka 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Apple Cinnamon Infused Vodka 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Cranberry Infused Vodka 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Lemon & Lavender Gin 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Orange & Bergamot Gin 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Pear Vodka 12/750ml', brandName: 'Wild Roots', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 154.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Peach Vodka 12/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 154.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Orange & Bergamot Gin 12/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 154.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Cucumber & Grapefruit Gin 12/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 154.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Raspberry Vodka 12/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 154.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Huckleberry Vodka 12/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 154.0, bottlePrice: 12.83 },
    { description: 'Wild Roots London Dry Gin 12/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 136.0, bottlePrice: 11.33 },
    { description: 'Wild Roots Grapefruit Vodka 12/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 154.0, bottlePrice: 12.83 },
    { description: 'Wild Roots Marionberry Lemonade Vodka Cocktail 6/4pks(355ml)', brandName: '', vintage: null, type: 'RTD', bottleSize: '355ml', bottlesPerCase: 6, casePrice: 48.0, bottlePrice: 2.0 },
    { description: 'Wild Roots Lemonade Vodka Cocktail 6/4pks(355ml)', brandName: '', vintage: null, type: 'RTD', bottleSize: '355ml', bottlesPerCase: 6, casePrice: 48.0, bottlePrice: 2.0 },
    { description: 'Wild Roots Huckleberry Lemonade Vodka Cocktail 6/4pks(355ml)', brandName: '', vintage: null, type: 'RTD', bottleSize: '355ml', bottlesPerCase: 6, casePrice: 48.0, bottlePrice: 2.0 },
    { description: 'Wild Roots Lemon Vodka & Soda 6/4pks(355ml)', brandName: '', vintage: null, type: 'RTD', bottleSize: '355ml', bottlesPerCase: 6, casePrice: 35.0, bottlePrice: 2.92 },
    { description: 'Wild Roots Blackberry Vodka & Soda 6/4pks(355ml)', brandName: '', vintage: null, type: 'RTD', bottleSize: '355ml', bottlesPerCase: 6, casePrice: 35.0, bottlePrice: 2.92 },
    { description: 'Wild Roots Peach Vodka & Soda 6/4pks(355ml)', brandName: '', vintage: null, type: 'RTD', bottleSize: '355ml', bottlesPerCase: 6, casePrice: 35.0, bottlePrice: 2.92 },
    { description: 'Wild Roots Raspberry Vodka & Soda 6/4pks(355ml)', brandName: '', vintage: null, type: 'RTD', bottleSize: '355ml', bottlesPerCase: 6, casePrice: 35.0, bottlePrice: 2.92 },
    { description: 'Wild Roots Marionberry Vodka 12/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 154.0, bottlePrice: 12.83 },
  ]},
  { name: 'Darling Drinks', paymentTerms: 'Net 30', products: [
    { description: 'NEW YORK DARLING IPA STYLE', brandName: '', vintage: null, type: 'Spirits', bottleSize: '12 FL OZ', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
    { description: 'DELHI DARLING GOLDEN- LAGER Style', brandName: '', vintage: null, type: 'Spirits', bottleSize: '12 FL OZ', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
  ]},
  { name: 'Don Vicente', paymentTerms: 'Net 45', products: [
    { description: 'Don Vicente Blanco', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 139.26, bottlePrice: 23.21 },
    { description: 'Don Vicente Reposado', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 168.42, bottlePrice: 28.07 },
    { description: 'Don Vicente Fuerte Reposado High Proof Tequila 6/750', brandName: 'Don Vicente', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 300.0, bottlePrice: 50.0 },
    { description: 'Don Vicente Fuerte Blanco High Proof Tequila 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 252.0, bottlePrice: 42.0 },
    { description: 'Don Vicente Blanco Tequila 6/750', brandName: 'Don Vicente', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 139.26, bottlePrice: 23.21 },
    { description: 'Don Vicente Reposado Tequila 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 168.42, bottlePrice: 28.07 },
  ]},
  { name: 'El Gran Legado de Vida', paymentTerms: 'Net 30', products: [
    { description: 'El Gran Legado De Vida Anejo Tequila 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 295.5, bottlePrice: 49.25 },
    { description: 'El Gran Legado De Vida Still Strength Blanco Tequila 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 118.2, bottlePrice: 19.7 },
    { description: 'El Gran Legado De Vida Blanco Tequila 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 171.42, bottlePrice: 28.57 },
    { description: 'El Gran Legado De Vida Reposado Tequila 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 204.0, bottlePrice: 34.0 },
  ]},
  { name: 'Falcon Spirits', paymentTerms: 'Net 30', products: [
    { description: 'Falcon Coffee Liquor', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 216.0, bottlePrice: 18.0 },
    { description: 'Fernet Francisco Manzanilla', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 216.0, bottlePrice: 18.0 },
    { description: 'Amaro Aplomado', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 216.0, bottlePrice: 18.0 },
    { description: 'Aperitivo Aplomado', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 192.0, bottlePrice: 16.0 },
    { description: 'Fernet Francisco Ruibarbo', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 216.0, bottlePrice: 18.0 },
    { description: 'Fernet Francisco Manzanilla 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 216.0, bottlePrice: 18.0 },
    { description: 'Fernet Francisco Ruibarbo 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 216.0, bottlePrice: 18.0 },
    { description: 'Botanica Vapor Infused Gin 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 216.0, bottlePrice: 18.0 },
    { description: 'Botanica Barrel Aged Gin 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 288.0, bottlePrice: 24.0 },
    { description: 'Aplomado Amaro 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 216.0, bottlePrice: 18.0 },
    { description: 'Aplomado Aperitivo 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 192.0, bottlePrice: 16.0 },
  ]},
  { name: 'Folktale Winery', paymentTerms: 'Net 60', products: [
    { description: '2022 Alias Pinot Noir, CA 12/750ml', brandName: '', vintage: null, type: 'Wine', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 66.0, bottlePrice: 11.0 },
    { description: 'Alias Pinot Noir, CA 12/750ml', brandName: 'Alias', vintage: null, type: 'Wine', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 66.0, bottlePrice: 5.5 },
    { description: 'Alias Pinot Noir 2023 12/750', brandName: 'Alias', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 66.0, bottlePrice: 5.5 },
  ]},
  { name: 'Freeland Spirits', paymentTerms: 'Net 30', products: [
    { description: 'Freeland Bourbon 6/750ml', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 147.0, bottlePrice: 24.5 },
    { description: 'Freeland Forest Gin 6/750ml', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 119.0, bottlePrice: 19.83 },
    { description: 'Freeland Cask Strength Bourbon', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 167.0, bottlePrice: 27.83 },
    { description: 'Freeland Cask Strength Bourbon Coit Liquor', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 167.0, bottlePrice: 27.83 },
    { description: 'Freeland Gin', brandName: 'Freeland Spirits', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 119.0, bottlePrice: 19.83 },
    { description: 'Freeland Bourbon', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 147.0, bottlePrice: 24.5 },
    { description: 'Freeland Rye Whiskey', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 250.0, bottlePrice: 41.67 },
    { description: 'Freeland Gin 3 pack', brandName: '', vintage: null, type: 'Spirits', bottleSize: '200ml', bottlesPerCase: 6, casePrice: 125.0, bottlePrice: 20.83 },
    { description: 'Freeland Chai Spice Liqueur', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 134.0, bottlePrice: 22.33 },
    { description: 'Freeland Dry Gin', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 122.0, bottlePrice: 20.33 },
    { description: 'Freeland Forest Gin', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 119.0, bottlePrice: 19.83 },
    { description: 'Freeland Cherry Blossom Liqueur', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 110.0, bottlePrice: 18.33 },
    { description: 'Freeland Cask Strength', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 164.0, bottlePrice: 27.33 },
    { description: 'Freeland Rye', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 250.0, bottlePrice: 41.67 },
    { description: 'Freeland Old Tom', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 120.0, bottlePrice: 20.0 },
    { description: 'Freeland Bourbon 3 pack', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 195.0, bottlePrice: 32.5 },
    { description: 'Freeland Gin Pride Edition', brandName: 'Freeland Spirits', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 119.0, bottlePrice: 19.83 },
    { description: 'Freeland Bourbon Cask Strength', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 167.0, bottlePrice: 27.83 },
    { description: 'Freeland Spirits Gin 6/750', brandName: 'Freeland Spirits', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 119.0, bottlePrice: 19.83 },
    { description: 'Freeland Spirits Bourbon 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 147.0, bottlePrice: 24.5 },
    { description: 'Freeland Bourbon Single Barrel "Argyle" ABV 58% 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 167.0, bottlePrice: 27.83 },
    { description: 'Freeland Spirits Rye Whiskey 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 250.0, bottlePrice: 41.67 },
    { description: 'Freeland Spirits Dry Gin 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 122.0, bottlePrice: 20.33 },
    { description: 'Freeland Chai Spice Liquor 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 134.0, bottlePrice: 22.33 },
    { description: 'Freeland Spirits Forest Gin 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 119.0, bottlePrice: 19.83 },
    { description: 'Freeland Spirits Bourbon Cask Strength 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 167.0, bottlePrice: 27.83 },
    { description: 'Freeland Spirits Pink Gin 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 119.0, bottlePrice: 19.83 },
    { description: 'Freeland Spirits Bourbon 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 147.0, bottlePrice: 24.5 },
  ]},
  { name: 'Heavenly Spirits', paymentTerms: 'Net 30', products: [
    { description: 'Rhum Baie des Tresors Agricole Flowers of the Winds', brandName: 'Heavenly Spirits', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 192.0, bottlePrice: 32.0 },
    { description: 'Rhum Baie des Tresors Agricole Martin Blanc Plein Soleil', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 144.0, bottlePrice: 24.0 },
    { description: 'Rhum Baie des Tresors Agricole Martin Fruits of the Rains', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 192.0, bottlePrice: 32.0 },
    { description: 'Monnet Sunshine Cognac', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 96.0, bottlePrice: 16.0 },
    { description: 'Guerin Vermouth Blanc 12pk', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 114.0, bottlePrice: 9.5 },
    { description: 'Guerin Vermouth Blanc Dry 12pk', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 114.0, bottlePrice: 9.5 },
    { description: 'Guerin Vermouth Rouge 12pk', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 114.0, bottlePrice: 9.5 },
    { description: 'Guerin Vermouth Rouge Dry 12pk', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 114.0, bottlePrice: 9.5 },
    { description: 'Yu Gin 6/700', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 114.0, bottlePrice: 19.0 },
    { description: 'Yu No Gin 6/700', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 108.0, bottlePrice: 18.0 },
    { description: 'Armorik Single Malt Sherry Cask Whiskey', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 168.0, bottlePrice: 28.0 },
    { description: 'Claque Pepin Calvados Fine', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 90.0, bottlePrice: 15.0 },
    { description: 'Claque Pepin Calvados Vieille Reserve Cert. Organic', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 132.0, bottlePrice: 22.0 },
    { description: 'Claque Pepin Calvados10 Year Old Cert. Organic', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 180.0, bottlePrice: 30.0 },
    { description: 'Dartigalongue Armagnac XO', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 150.0, bottlePrice: 25.0 },
    { description: 'Dartigalongue Armagnac Hors d\'Age', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 192.0, bottlePrice: 32.0 },
    { description: 'Noces Royales Pear Cognac Liqueur 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 108.0, bottlePrice: 18.0 },
    { description: 'Guerin Vermouth Blanc 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 114.0, bottlePrice: 9.5 },
    { description: 'Guerin Vermouth Blanc Dry 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 114.0, bottlePrice: 9.5 },
    { description: 'Guerin Vermouth Rouge 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 114.0, bottlePrice: 9.5 },
    { description: 'Guerin Vermouth Rouge Dry 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 114.0, bottlePrice: 9.5 },
    { description: 'Claque Pepin Calvados Fine 12/375', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 12, casePrice: 108.0, bottlePrice: 9.0 },
    { description: 'Claque Pepin Calvados10 Year Old Cert. Organic 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 186.0, bottlePrice: 31.0 },
    { description: 'Dartigalongue Armagnac XO 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 162.0, bottlePrice: 27.0 },
    { description: 'Dartigalongue Armagnac Hors d\'Age 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 222.0, bottlePrice: 37.0 },
    { description: 'Dartigalongue 1978 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 113.0 },
    { description: 'Monnet Cognac VSOP 6/700ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 126.0, bottlePrice: 21.0 },
    { description: 'Yu Gin 6/700ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 114.0, bottlePrice: 19.0 },
    { description: 'Dartigalongue Bas Armagnac Hors d\'Age 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 222.0, bottlePrice: 37.0 },
    { description: 'Claque-Pepin Calvados Fine 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 90.0, bottlePrice: 15.0 },
    { description: 'Noces Royales Cognac and Pear Williams Liqueur6/700ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 108.0, bottlePrice: 18.0 },
    { description: 'Claque Pepin Calvados Fine 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 90.0, bottlePrice: 15.0 },
    { description: 'Claque Pepin Calvados Vieille Reserve Cert. Organic 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 132.0, bottlePrice: 22.0 },
    { description: 'Dartigalongue Armagnac Dry Cellar, Dry cellar aged 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 114.0, bottlePrice: 19.0 },
    { description: 'Dartigalongue Armagnac Un-Oaked, Blanche 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 96.0, bottlePrice: 16.0 },
    { description: 'Rhum Baie des Tresors Agricole Martin Blanc Plein Soleil 6/700', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 132.0, bottlePrice: 22.0 },
    { description: 'Guerin Pineau des Charentes Tradition White 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 60.0, bottlePrice: 10.0 },
    { description: 'Guerin Pineau des Charentes Tradition Red 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 60.0, bottlePrice: 10.0 },
    { description: 'Monnet VSOP Cognac Capiello 6/700', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 126.0, bottlePrice: 21.0 },
  ]},
  { name: 'Jackson Temple Spirits LLC', paymentTerms: 'Net 30', products: [
    { description: 'Hornbrook Ten Point Gin', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 124.0, bottlePrice: 20.67 },
    { description: 'Hornbrook Linen Gin', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 124.0, bottlePrice: 20.67 },
    { description: 'Hornbrook Linen Gin 6/750', brandName: 'Hornbrook', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 124.0, bottlePrice: 20.67 },
    { description: 'Hornbrook Ten Point Gin 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 124.0, bottlePrice: 20.67 },
  ]},
  { name: 'Kapena Tequila', paymentTerms: 'Net 30', products: [
    { description: 'Kapena Li Hing Infused Tequila 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 168.0, bottlePrice: 28.0 },
    { description: 'Kapena Hawaiian Chili Infused Reposado Tequila 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 168.0, bottlePrice: 28.0 },
    { description: 'Kapena Silver 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 168.0, bottlePrice: 28.0 },
  ]},
  { name: 'Koena Bev LLC', paymentTerms: 'Net 45', products: [
    { description: 'Yeyo Tequila Blanco', brandName: 'Yeyo', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 145.0, bottlePrice: 24.17 },
    { description: 'Yeyo Day of The Dead Joven Luna 6x750', brandName: 'Yeyo', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 305.0, bottlePrice: 50.83 },
    { description: 'Yeyo Day of The Dead Joven Sol 6x750', brandName: 'Yeyo', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 305.0, bottlePrice: 50.83 },
    { description: 'Yeyo Tequila Reposado', brandName: 'Yeyo', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Yeyo Tequila Reposado 6x750', brandName: 'Yeyo', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Yéyo Tequila Reposado ROSA 86 6/750', brandName: 'Yeyo', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Yéyo Tequila Day of The Dead Joven Sol Vol. 2 6/750', brandName: 'Yeyo', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 305.0, bottlePrice: 50.83 },
    { description: 'Yéyo Tequila Day of The Dead Joven Luna Vol. 2 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 305.0, bottlePrice: 50.83 },
    { description: 'Yéyo Tequila Reposado - Batch 1 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Yéyo Tequila Reposado Agave Vice 89 6/750ml **PALLET 1**', brandName: 'Yeyo', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 265.0, bottlePrice: 44.17 },
    { description: 'Yéyo Tequila Reposado Agave Vice 89 (Vista) 6/750ml **PALLET 2**', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 265.0, bottlePrice: 44.17 },
    { description: 'Yéyo Tequila Blanco - Batch 150 6/750 **PALLET 3**', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 145.0, bottlePrice: 24.17 },
    { description: 'Yéyo Tequila Reposado Agave Vice 89 6/750ml', brandName: 'Yéyo', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 265.0, bottlePrice: 44.17 },
    { description: 'Yéyo Tequila Blanco - Batch 150 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 145.0, bottlePrice: 24.17 },
    { description: 'Yéyo Tequila Blanco - Batch 150 6/750 (SAMPLES)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
    { description: 'Yéyo Tequila High Proof Blanco 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 200.0, bottlePrice: 33.33 },
  ]},
  { name: 'La Shikis Mexican Spirits', paymentTerms: 'Net 30', products: [
    { description: 'El Gran Legado de Vida Anejo', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 295.5, bottlePrice: 49.25 },
  ]},
  { name: 'Lefty O\'Doul\'s', paymentTerms: 'Net 30', products: [
    { description: 'Lefty O\'Doul\'s Bloody Mary Mix 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 12, casePrice: 40.0, bottlePrice: 3.33 },
    { description: 'Lefty O\'Doul\'s Margarita Mix 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 12, casePrice: 40.0, bottlePrice: 3.33 },
    { description: 'Lefty O\'Doul\'s Agave Nectar 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 12, casePrice: 62.0, bottlePrice: 5.17 },
  ]},
  { name: 'Liber & Co.', paymentTerms: 'Net 60', products: [
    { description: 'Liber & Co. Real Grenadine 6/750mL', brandName: 'Liber Cocktails', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Liber & Co. Pineapple Gum Syrup 6/750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Liber & Co. Almond Orgeat Syrup 6/750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Liber & Co. Toasted Coconut Syrup 6/750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Premium Tonic Syrup - 375mL', brandName: 'Liber Cocktails', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Premium Tonic Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Texas Grapefruit Shrub - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Texas Grapefruit Shrub - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Fiery Ginger Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Fiery Ginger Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Classic Gum Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Classic Gum Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Pineapple Gum Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Pineapple Gum Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Real Grenadine - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Real Grenadine - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Almond Orgeat Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Almond Orgeat Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Demerara Gum Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Demerara Gum Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Tropical Passionfruit Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Tropical Passionfruit Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Caramelized Fig Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Caramelized Fig Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Rio Red Grapefruit Cordial - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Rio Red Grapefruit Cordial - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Blood Orange Cordial - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Blood Orange Cordial - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Sugarcane Kola Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Sugarcane Kola Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Raspberry Gum Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Raspberry Gum Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Toasted Coconut Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Toasted Coconut Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Old Fashioned Cocktail Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Old Fashioned Cocktail Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Pacific Strawberry Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Pacific Strawberry Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Yakima Valley Peach Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Yakima Valley Peach Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Marion Blackberry Syrup - 375mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Marion Blackberry Syrup - 750 mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Lemon Lavender Cordial - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Liber & Co. Blood Orange Cordial 6/750mL', brandName: 'Liber Cocktails', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Liber & Co. Rio Red Grapefruit Cordial 6/750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Liber & Co. Marion Blackberry Syrup 6/750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Liber & Co. Old Fashioned Cocktail Syrup 6/750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Liber & Co. Demerara Gum Syrup 6/750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Liber & Co. Raspberry Gum Syrup 6/750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Liber & Co. Lemon Lavender Cordial 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Liber & Co. Pacific Strawberry Syrup 6/750mL', brandName: 'Liber Cocktails', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Cinnamon Syrup - 750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Real Grenadine -375mL', brandName: 'Liber & Co.', vintage: null, type: 'Spirits', bottleSize: '375ml', bottlesPerCase: 6, casePrice: 52.52, bottlePrice: 8.75 },
    { description: 'Yakima Valley Peach Syrup - 6/750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
    { description: 'Marion Blackberry Syrup - 750mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 69.8, bottlePrice: 11.63 },
  ]},
  { name: 'Limestone Farms', paymentTerms: 'Net 30', products: [
    { description: 'Bloodlines Straight Bourbon', brandName: 'Limestone Farms', vintage: null, type: 'Bourbon', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 165.0, bottlePrice: 27.5 },
    { description: 'Bloodlines Small Batch Bourbon', brandName: 'Limestone Farms', vintage: null, type: 'Bourbon', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 222.0, bottlePrice: 37.0 },
    { description: 'Single Barrel Program', brandName: 'Limestone Farms', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 368.0, bottlePrice: 61.33 },
    { description: '"Morgan Family" Private Stock Kentucky Straight Whiskey 6/750', brandName: 'Limestone Farms', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 580.0, bottlePrice: 96.67 },
    { description: '"Morgan Family" Select Batch Kentucky Straight Whiskey 6/750', brandName: 'Limestone Farms', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 280.0, bottlePrice: 46.67 },
  ]},
  { name: 'Loco Tequila', paymentTerms: 'Net 30', products: [
    { description: 'Loco Blanco Tequila 6/750', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 445.5, bottlePrice: 74.25 },
    { description: 'Loco Ámbar Tequila 6/750', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 657.7, bottlePrice: 109.62 },
    { description: 'Loco Puro Corazón Tequila 6/750', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 1151.7, bottlePrice: 191.95 },
  ]},
  { name: 'MEXA Brands', paymentTerms: 'Net 30', products: [
    { description: 'Hijos de Zoila Mezcal', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 97.0, bottlePrice: 16.17 },
    { description: 'Hijos De Zoila 100% Maguey Espadin 6/750ml', brandName: 'Hijos de Zoila Mezcal', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 97.0, bottlePrice: 16.17 },
    { description: 'Hijos de Zoila Mezcal 6/750ml', brandName: 'Hijos de Zoila Mezcal', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 97.0, bottlePrice: 16.17 },
  ]},
  { name: 'MHW / Cihuatán', paymentTerms: 'Net 45', products: [
    { description: 'Cihuatán Jade - Aged Rum 4YO 6/700', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 63.0, bottlePrice: 10.5 },
    { description: 'Cihuatán Indigo - Aged Rum 8YO 6/700', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 90.0, bottlePrice: 15.0 },
    { description: 'Cihuatán Cinabrio - Aged Rum 12YO 6/700', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 115.0, bottlePrice: 19.17 },
    { description: 'Cihuatán Artesano - Aged Rum 10YO6/700', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 115.0, bottlePrice: 19.17 },
    { description: 'Cihuatán Limited Edition Suerte - Aged Rum 6/700', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 291.0, bottlePrice: 48.5 },
    { description: 'Cihuatán XAMAN XO - Aged Rum 16YO 3/700', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 207.0, bottlePrice: 69.0 },
    { description: '*Cihuatán Jade - Aged Rum 4YO 6/700 (SAMPLES)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
    { description: '*Cihuatán Indigo - Aged Rum 8YO 6/700 (SAMPLES)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
    { description: '*Cihuatán Cinabrio - Aged Rum 12YO 6/700 (SAMPLES)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
    { description: '*Cihuatán Artesano - Aged Rum 10YO6/700 (SAMPLES)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
    { description: '*Cihuatán Limited Edition Suerte - Aged Rum 6/700 (SAMPLES)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
    { description: 'Cihuatán Artesano - Aged Rum 10YO 6/700', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 105.0, bottlePrice: 17.5 },
    { description: 'Cihuatán Jade - Aged Rum 4YO 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 12, casePrice: 144.0, bottlePrice: 12.0 },
    { description: '*Cihuatán Artesano - Aged Rum 10YO 6/700 (SAMPLES)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
    { description: '*Cihuatán Jade - Aged Rum 4YO 12/1L (SAMPLES)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 12, casePrice: 0.0, bottlePrice: 0.0 },
  ]},
  { name: 'MHW / The Illusionist', paymentTerms: 'Net 60', products: [
    { description: 'The Illusionist Dry Gin 6x700ml', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 135.0, bottlePrice: 22.5 },
    { description: 'Illusionist Dry Gin 6/700', brandName: '', vintage: null, type: 'Spirit', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 117.0, bottlePrice: 19.5 },
  ]},
  { name: 'MHW / Vagabond Spirit Co.', paymentTerms: 'Net 30', products: [
    { description: 'Tierra de Ensueño Blanco Tequila Batch #4 6/750ml', brandName: 'Tierra de Ensueño', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Tierra de Ensueño Single Barrel Reposado Weller Barrels.', brandName: 'Tierra de Ensueño', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 260.0, bottlePrice: 43.33 },
    { description: 'Tierra de Ensueño Blanco Tequila Batch #5 6/750mL', brandName: 'Tierra de Ensueño', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Tierra de Ensueño Blanco Tequila Batch #6 6/750ml', brandName: 'Tierra de Ensueño', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Tierra de Ensueño Blanco Tequila Batch #7 6/750ml VAG2025BLA750N07', brandName: '', vintage: 'Tierra de Ensueño', type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Tierra de Ensueño Reposado Tequila - Wheated Bourbon Cask 6/750ml VAG2025REP750N01', brandName: 'Tierra de Ensueño', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 225.0, bottlePrice: 37.5 },
    { description: 'Tierra de Ensueño Blanco Tequila Batch #6 6/750ml VAG2025BLA750N06', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Tierra de Ensueño Single Barrel Reposado - Rum Cask Rested (VAG24REP-SB-RUM)', brandName: 'Tierra de Ensueño', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 260.0, bottlePrice: 43.33 },
    { description: 'Tierra de Ensueño Reposado Tequila - Wheated Bourbon Cask Batch #2 (VAG2025REP750NO2)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 225.0, bottlePrice: 37.5 },
    { description: 'Tierra de Ensueño Blanco Tequila Batch #8 6/750ml VAG2025BLA750N08', brandName: 'Tierra de Ensueño', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Tierra de Ensueño Single Barrel Anejo 6/750ml VAG25-ANJ-SB-CHERRY', brandName: 'Tierra de Ensueño', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 320.0, bottlePrice: 53.33 },
    { description: 'Tierra de Ensueño Reposado Tequila Batch #3 - Wheated Bourbon Cask 6/750ml VAG2025REP750NO3', brandName: 'Tierra de Ensueño', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 225.0, bottlePrice: 37.5 },
    { description: 'Tierra de Ensueño Blanco Tequila Batch #9 6/750ml VAG2025BLA750N09', brandName: 'Tierra de Ensueño', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
  ]},
  { name: 'Mezo Beverages', paymentTerms: 'Net 30', products: [
    { description: 'Mezo Mezcal Cocktails Piña Mezorita 6/4pks(12oz)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '12oz', bottlesPerCase: 6, casePrice: 45.0, bottlePrice: 1.88 },
    { description: 'Mezo Mezcal Cocktails Guava Mezorita 6/4pks(12oz)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '12oz', bottlesPerCase: 6, casePrice: 45.0, bottlePrice: 1.88 },
  ]},
  { name: 'Morningside Brands, Inc.', paymentTerms: 'Net 30', products: [
    { description: 'Tequila Blanco', brandName: 'Alma del Jaguar', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 160.0, bottlePrice: 26.67 },
    { description: 'Tequila Reposado', brandName: 'Alma del Jaguar', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 195.0, bottlePrice: 32.5 },
    { description: 'Tequila Anejo', brandName: 'Alma del Jaguar', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 250.0, bottlePrice: 41.67 },
    { description: 'Alma del Jaguar Single Barrel Anejo #17 (Mira Lomo Market)', brandName: 'Alma del Jaguar', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 280.0, bottlePrice: 46.67 },
    { description: 'Alma del Jaguar Single Barrel Anejo #18 (Hi Proof Fullerton)', brandName: 'Alma del Jaguar', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 280.0, bottlePrice: 46.67 },
    { description: 'Alma del Jaguar Single Barrel Anejo #19 (ACS)', brandName: 'Alma del Jaguar', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 280.0, bottlePrice: 46.67 },
    { description: 'Alma del Jaguar Single Barrel Anejo #20 (El Cerrito Liquor)', brandName: 'Alma del Jaguar', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 280.0, bottlePrice: 46.67 },
    { description: 'Alma del Jaguar Single Barrel Anejo #111 (ACS)', brandName: 'Alma del Jaguar', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 280.0, bottlePrice: 46.67 },
    { description: 'Alma del Jaguar Tequila Blanco', brandName: 'Alma del Jaguar', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 160.0, bottlePrice: 26.67 },
    { description: 'Alma del Jaguar Tequila Reposado', brandName: 'Alma del Jaguar', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 195.0, bottlePrice: 32.5 },
    { description: 'Alma del Jaguar Tequila Anejo', brandName: 'Alma del Jaguar', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 250.0, bottlePrice: 41.67 },
    { description: 'Alma del Jaguar Tequila Blanco 6/750', brandName: 'Alma del Jaguar', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 160.0, bottlePrice: 26.67 },
    { description: 'Alma del Jaguar Tequila Reposado 6/750', brandName: '', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 195.0, bottlePrice: 32.5 },
    { description: 'Alma del Jaguar Tequila Anejo 6/750', brandName: '', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 250.0, bottlePrice: 41.67 },
    { description: 'Alma del Jaguar Nocturna 6/750', brandName: 'Alma del Jaguar', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Alma del Jaguar Single Barrel Anejo (Cypress) 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 280.0, bottlePrice: 46.67 },
    { description: 'Alma del Jaguar Anejo 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 250.0, bottlePrice: 41.67 },
    { description: 'Alma del Jaguar Barricas Anejo Apple', brandName: 'Alma del Jaguar', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 420.0, bottlePrice: 70.0 },
    { description: 'Alma del Jaguar Barricas Reposado Pear Wood', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 420.0, bottlePrice: 70.0 },
    { description: 'Alma del Jaguar Barricas Anejo Mizunara', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 480.0, bottlePrice: 80.0 },
    { description: 'Alma del Jaguar Barricas Anejo Ruby Wine', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 420.0, bottlePrice: 70.0 },
    { description: 'Alma del Jaguar Barricas Anejo Vino De Naranja', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 420.0, bottlePrice: 70.0 },
    { description: 'Alma del Jaguar Tequila Blanco - High Proof "Nocturna" 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Alma del Jaguar Barricas Anejo Mizunara 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 480.0, bottlePrice: 80.0 },
    { description: '*Alma del Jaguar Barricas Anejo Mizunara 6/750 (SAMPLES)', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
  ]},
  { name: 'Old Hillside', paymentTerms: 'Net 45', products: [
    { description: 'Old Hillside Founders Select', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 165.0, bottlePrice: 27.5 },
    { description: 'Old Hillside Trifecta', brandName: 'Old Hillside', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 200.0, bottlePrice: 33.33 },
    { description: 'Old Hillside Rye', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 188.0, bottlePrice: 31.33 },
    { description: 'Old Hillside Trifecta 6/750', brandName: 'Old Hillside', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 200.0, bottlePrice: 33.33 },
    { description: 'Old Hillside Straight Rye Whiskey “The Last Rye\'d" 5 Year 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 188.0, bottlePrice: 31.33 },
    { description: 'Old Hillside Hellfighters 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 310.0, bottlePrice: 51.67 },
    { description: 'Old Hillside Kentucky Straight Bourbon Whiskey 6/750', brandName: 'Old Hillside', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 179.0, bottlePrice: 29.83 },
  ]},
  { name: 'Old Louisville Whiskey', paymentTerms: 'Net 45', products: [
    { description: 'KY Series Bourbon Batch 8 Years 6/750ml', brandName: 'Old Louisville Whiskey', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 180.0, bottlePrice: 30.0 },
  ]},
  { name: 'Outpost Spirits LLC', paymentTerms: 'Net 30', products: [
    { description: 'Outpost Whiskey 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 12, casePrice: 156.0, bottlePrice: 13.0 },
    { description: 'Outpost Gin 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 81.0, bottlePrice: 6.75 },
    { description: 'Outpost Vodka 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 73.4, bottlePrice: 6.12 },
  ]},
  { name: 'PL Brands Inc', paymentTerms: 'Net 30', products: [
    { description: 'Alta Azul Tequila Blanco 12/750ml', brandName: 'Alta Azul Tequila', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 105.0, bottlePrice: 8.75 },
    { description: 'Alta Azul Tequila Blanco 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 120.0, bottlePrice: 10.0 },
    { description: 'Alta Azul Tequila Blanco 6/1.75L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 93.0, bottlePrice: 7.75 },
    { description: 'Alta Azul Tequila Reposado 12/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 111.0, bottlePrice: 9.25 },
    { description: 'Alta Azul Tequila Reposado 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 126.0, bottlePrice: 10.5 },
    { description: 'Alta Azul Tequila Reposado 6/1.75L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 99.0, bottlePrice: 8.25 },
  ]},
  { name: 'Palazzo Wine', paymentTerms: 'Net 30', products: [
    { description: '2019 Cabernet Franc – RESERVE 12/750ml', brandName: 'Palazzo', vintage: '2019', type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 282.0, bottlePrice: 23.5 },
  ]},
  { name: 'Park Street Imports', paymentTerms: 'Net 30', products: [
    { description: 'Zumbador Tequila Blanco 12x750ml', brandName: 'Zumbador', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 140.0, bottlePrice: 11.67 },
    { description: 'Zumbador Tequila Blanco 12x1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 12, casePrice: 157.0, bottlePrice: 13.08 },
    { description: 'Zumbador Tequila Reposado 12x750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 175.0, bottlePrice: 14.58 },
    { description: 'Granja Nomada Espadin Mezcal 6x1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 6, casePrice: 111.0, bottlePrice: 18.5 },
    { description: 'Granja Nomada Espadin Mezcal 6x750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 107.0, bottlePrice: 0.0 },
    { description: 'Granja Nomada Ensamble Mezcal 6x750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 157.0, bottlePrice: 0.0 },
    { description: 'Aguaviva Cachaca 12x750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 78.0, bottlePrice: 0.0 },
    { description: 'English Harbour Rum Sherry Cask Finish 6/700mL', brandName: '', vintage: null, type: 'Spirit', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 142.75, bottlePrice: 23.79 },
    { description: 'English Harbour Madeira Cask Finish 6/700mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 142.75, bottlePrice: 23.79 },
    { description: 'English Harbour Port Cask Finish 6/700mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 142.75, bottlePrice: 23.79 },
    { description: 'Engish Harbour Rum 90th Anniversary 6/700mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 300.0, bottlePrice: 50.0 },
    { description: 'English Harbour Rum 5 year Old 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 86.0, bottlePrice: 14.33 },
    { description: 'English Harbour Rum 10 Year Old 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 174.5, bottlePrice: 29.08 },
    { description: 'English Harbour Silver 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 12, casePrice: 109.0, bottlePrice: 9.08 },
    { description: 'English Harbour Gold 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 12, casePrice: 109.0, bottlePrice: 9.08 },
    { description: 'Wooden Barrel Cups 180/255mL', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
    { description: 'Kilinga Bacanora Blanco 6/750ml', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 150.4, bottlePrice: 25.07 },
    { description: 'Wicked Blueberry Gin 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.5, bottlePrice: 12.92 },
    { description: 'Wicked Raspberry Gin 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 77.5, bottlePrice: 12.92 },
    { description: 'Entremanos Tequila Blanco 6x700ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 166.0, bottlePrice: 27.67 },
    { description: '1953 Tequila Anejo 4/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 4, casePrice: 445.0, bottlePrice: 0.0 },
    { description: 'Zumbador Tequila Blanco 12/750ml', brandName: 'Zumbador', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 140.0, bottlePrice: 11.67 },
    { description: 'Zumbador Tequila Reposado 12/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 175.0, bottlePrice: 14.58 },
    { description: 'Zumbador Tequila Single Barrel Anejo # 20 (Hi Proof) 12/750', brandName: 'Zumbador', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 270.0, bottlePrice: 22.5 },
    { description: 'Zumbador Tequila Single Barrel Anejo # 16 (Bleu Wine & Spirits) 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 270.0, bottlePrice: 22.5 },
    { description: 'Zumbador Tequila Single Barrel Anejo #19 (Old Town) 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 270.0, bottlePrice: 22.5 },
    { description: 'Zumbador Tequila Single Barrel Anejo #15 (El Cerrito Liquor) 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 270.0, bottlePrice: 22.5 },
    { description: 'Zumbador Tequila Single Barrel Anejo #18 (Mira Loma Market) 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 270.0, bottlePrice: 22.5 },
    { description: 'Zumbador Tequila Single Barrel Anejo #13 (ACS Barrel) 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 270.0, bottlePrice: 22.5 },
    { description: 'Zumbador Tequila Anejo 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 220.0, bottlePrice: 18.33 },
    { description: 'Entremanos Tequila Primavera 6x700ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Entremanos Tequila Blanco High Proof 6/700', brandName: '', vintage: null, type: 'Spirits', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
    { description: 'TC CRAFT Tequila Blanco 6/750', brandName: 'TC CRAFT', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
    { description: 'TC CRAFT Tequila Reposado 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 0.0, bottlePrice: 0.0 },
    { description: 'Zumbador Tequila Blanco 12/750', brandName: 'Zumbador', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 140.0, bottlePrice: 11.67 },
    { description: 'Zumbador Tequila Reposado 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 175.0, bottlePrice: 14.58 },
    { description: 'Zumbador Tequila Single Barrel Anejo #2 (Hunter of Bottles Barrel) 12/750ml', brandName: 'Zumbador', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 270.0, bottlePrice: 22.5 },
    { description: 'Zumbador Tequila Single Barrel Anejo #8 (Tequila Tasting Session) 12/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 270.0, bottlePrice: 22.5 },
    { description: 'Zumbador Tequila Blanco 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 12, casePrice: 157.0, bottlePrice: 13.08 },
    { description: 'Kokocaribe Coconut Rum 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 12, casePrice: 109.0, bottlePrice: 9.08 },
    { description: 'Zumbador Tequila High Proof Blanco 12/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 235.0, bottlePrice: 19.58 },
    { description: 'Zumbador Tequila Anejo 12/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 220.0, bottlePrice: 18.33 },
    { description: 'Manuscrito Blanco (Chapter 1) 6/750ml', brandName: 'Manuscrito', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 150.0, bottlePrice: 25.0 },
    { description: 'Manuscrito Blanco High Proof (Chapter 2) 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 186.0, bottlePrice: 31.0 },
    { description: 'Manuscrito Reposado (Chapter 3) 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 165.0, bottlePrice: 27.5 },
    { description: 'Manuscrito Reposado High Proof (Chapter 4) 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 200.0, bottlePrice: 33.33 },
    { description: 'Manuscrito Blanco (Chapter 1) 6/750 ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 150.0, bottlePrice: 25.0 },
    { description: 'Manuscrito Blanco High Proof (Chapter 2) 6/750 ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 186.0, bottlePrice: 31.0 },
    { description: 'Manuscrito Reposado (Chapter 3) 6/750 ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 165.0, bottlePrice: 27.5 },
  ]},
  { name: 'Rocketship Brand Company', paymentTerms: 'Net 60', products: [
    { description: 'El Magico Tequila Blanco 6/750', brandName: 'El Magico', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 149.0, bottlePrice: 24.83 },
    { description: 'El Magico Tequila Reposado 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 165.0, bottlePrice: 27.5 },
    { description: 'Dancing Panda 4 yr 6/750', brandName: 'Dancing Panda Bourbon', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 127.0, bottlePrice: 21.17 },
    { description: 'Dancing Panda 8 yr 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 191.0, bottlePrice: 31.83 },
    { description: 'Dancing Panda 10 yr 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 272.0, bottlePrice: 45.33 },
    { description: 'El Magico Tequila Anejo 6/750', brandName: 'El Magico Tequila', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 198.0, bottlePrice: 33.0 },
    { description: 'Lasso Motel 18YR American STRGHT Whiskey 6/750', brandName: 'Lasso Motel Bourbon', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 400.0, bottlePrice: 66.67 },
    { description: 'Lasso Motel 4YR KY STRGHT Whiskey 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 158.0, bottlePrice: 26.33 },
    { description: 'Lasso Motel 8YR KY STRGHT Whiskey 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 245.0, bottlePrice: 40.83 },
    { description: 'Lasso Motel Darts Kentucky Straight Bourbon 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 212.0, bottlePrice: 35.33 },
    { description: 'Lasso Motel SNGL BRRL Cask Strength Rye 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 280.0, bottlePrice: 46.67 },
    { description: 'Lasso Motel Wheated Kentucky Straight Bourbon 4yr 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 159.0, bottlePrice: 26.5 },
    { description: 'Painted Donkey Tequila Blanco 12/750', brandName: 'Painted Donkey Tequila Blanco', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 158.0, bottlePrice: 1896.0 },
    { description: 'Painted Donkey Tequila Cafe 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 150.0, bottlePrice: 12.5 },
    { description: 'Painted Donkey Tequila Lime 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 150.0, bottlePrice: 12.5 },
    { description: 'Painted Donkey Tequila Pineapple 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 150.0, bottlePrice: 12.5 },
    { description: 'Painted Donkey Tequila Reposado 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 164.19, bottlePrice: 1970.28 },
    { description: 'Painted Donkey Tequila Watermelon 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 150.0, bottlePrice: 12.5 },
    { description: 'Painted Donkey Tequila Blanco 6/1.75', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1.75L', bottlesPerCase: 6, casePrice: 164.19, bottlePrice: 27.36 },
    { description: 'El Magico Tequila Reposado 6/750ml', brandName: 'El Magico Tequila', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 165.0, bottlePrice: 27.5 },
    { description: 'El Magico Tequila Blanco 6/750ml', brandName: 'El Magico Tequila', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 149.0, bottlePrice: 24.83 },
    { description: 'El Magico Tequila Anejo 6/750ml', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 198.0, bottlePrice: 33.0 },
  ]},
  { name: 'San Francisco Distilling Co.', paymentTerms: 'Net 30', products: [
    { description: 'Outpost Gin', brandName: 'SF Distilling', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 81.0, bottlePrice: 6.75 },
    { description: 'Outpost Vodka', brandName: 'SF Distilling', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 73.4, bottlePrice: 6.12 },
    { description: 'Forty Nine Mile Straight Bourbon Whiskey 7 Year 12/750', brandName: 'SF Distilling', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 294.0, bottlePrice: 24.5 },
    { description: 'Forty Below Gin 12/750', brandName: 'SF Distilling', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 161.0, bottlePrice: 13.42 },
    { description: 'Forty Nine Mile Straight Bourbon Whiskey Single Barrel 7 Year 12/750', brandName: 'SF Distilling', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 472.15, bottlePrice: 39.35 },
    { description: 'Outpost Vodka 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 12, casePrice: 73.4, bottlePrice: 6.12 },
    { description: 'Outpost Gin 12/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 81.0, bottlePrice: 6.75 },
    { description: 'Forty Nine Mile Straight Bourbon Whiskey 10 Year Single Barrel (Healthy Spirits) 12/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 12, casePrice: 672.0, bottlePrice: 56.0 },
  ]},
  { name: 'TC Craft Tequila', paymentTerms: 'Net 30', products: [
    { description: 'TC CRAFT Tequila Anejo 6/750', brandName: 'TC CRAFT', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 211.68, bottlePrice: 35.28 },
    { description: 'TC CRAFT Non-Alc Margarita Mix 6/1L', brandName: '', vintage: null, type: 'Spirits', bottleSize: '1L', bottlesPerCase: 6, casePrice: 30.24, bottlePrice: 5.04 },
    { description: 'TC CRAFT Tequila Blanco 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 136.02, bottlePrice: 22.67 },
    { description: 'TC CRAFT Tequila Reposado 6/750', brandName: '', vintage: null, type: 'Spirits', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 156.0, bottlePrice: 26.0 },
  ]},
  { name: 'TEQUILAS TINAJAS DE MÉXICO', paymentTerms: 'Net 60', products: [
    { description: 'TEQUILA "ENTREMANOS" JOVEN 100% AGAVE AZUL (Barrel Selection “PYROLOU”) 6/700ml.', brandName: 'Entremanos', vintage: null, type: 'Spirit', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 197.0, bottlePrice: 32.83 },
    { description: 'Entremanos Tequila Primavera 6/700', brandName: 'Entremanos', vintage: null, type: 'Spirit', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 210.0, bottlePrice: 35.0 },
    { description: 'Entremanos Tequila Blanco 6/700', brandName: '', vintage: null, type: 'Spirit', bottleSize: '700ml', bottlesPerCase: 6, casePrice: 166.0, bottlePrice: 0.0 },
  ]},
  { name: 'Tequila General Gorostieta', paymentTerms: 'Net 45', products: [
    { description: 'Tequila General Gorostieta Blanco Standard Box 6/750', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 181.5, bottlePrice: 30.25 },
    { description: 'Tequila General Gorostieta Joven Luxury Box 6/750', brandName: '', vintage: null, type: 'Spirit', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 300.0, bottlePrice: 50.0 },
    { description: 'Tequila General Gorostieta Reposado', brandName: 'Tequila General Gorostieta', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 216.0, bottlePrice: 36.0 },
    { description: 'Tequila General Reposado', brandName: 'Tequila General Gorostieta', vintage: null, type: 'Tequila', bottleSize: '750ml', bottlesPerCase: 6, casePrice: 216.0, bottlePrice: 36.0 },
  ]},
];
